baseURL = 'https://timbueno.com/'
languageCode = 'en-us'
title = 'Tim Bueno'
theme = 'hugo-bearblog'

[params]
    hideMadeWithLine = true

[outputs]
    home = ["html", "rss"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
	
[module]
  [[module.mounts]]
    excludeFiles = 'blog/^(?=.*!)(?=.*[Tt]emplate).*\.md$'
    source = 'content'
    target = 'content'